version: '3'

services:
  backend:
    container_name: mern-backend
    build: ./server
    ports:
      - "8080:8080"
    # depends_on:
    #   - mongo
    environment:
      - CLIENT=http://localhost:5173
      - PORT=8080
      - SERVER=http://localhost:8080
      - MONGOD_URL=mongodb://127.0.0.1:27017/AppFest
      - STRIPE_SECRET=sk_test_51IfPckI9Cx0UeZSmapKoMoaL4ro0Nk7zRpiI8jlUjwCMHUIF5SJ836Ma31Xv7WdB7Lb25NjzQP3krHqi7oe6wjsk001G51IKdF

  frontend:
    container_name: mern-frontend
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_SERVER = http://localhost:8080/
