version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
      - ./server/.env
      - ./client/.env
    volumes:
      - './server:/app/server'
      - './client/build:/app/client/build'
